In [11]:
import pandas as pd
df = pd.read_csv("wines_SPA.CSV")

df

,winery,wine,year,rating,num_reviews,country,region,price,type,body,acidity
0,Teso La Monja,Tinto,2013,4.9,58,Espana,Toro,995.00,Toro Red,5.0,3.0
1,Artadi,Vina El Pison,2018,4.9,31,Espana,Vino de Espana,313.50,Tempranillo,4.0,2.0
2,Vega Sicilia,Unico,2009,4.8,1793,Espana,Ribera del Duero,324.95,Ribera Del Duero Red,5.0,3.0
3,Vega Sicilia,Unico,1999,4.8,1705,Espana,Ribera del Duero,692.96,Ribera Del Duero Red,5.0,3.0
4,Vega Sicilia,Unico,1996,4.8,1309,Espana,Ribera del Duero,778.06,Ribera Del Duero Red,5.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
7495,Contino,Reserva,2016,4.2,392,Espana,Rioja,19.98,Rioja Red,4.0,3.0
7496,Conreria d'Scala Dei,Les Brugueres,2018,4.2,390,Espana,Priorato,16.76,Priorat Red,4.0,3.0
7497,Mustiguillo,Finca Terrerazo,2017,4.2,390,Espana,El Terrerazo,24.45,Red,4.0,3.0
7498,Matarromera,Gran Reserva,2011,4.2,389,Espana,Ribera del Duero,64.50,Ribera Del Duero Red,5.0,3.0
7499,Sei Solo,Preludio,2016,4.2,388,Espana,Ribera del Duero,31.63,Ribera Del Duero Red,5.0,3.0

In [12]:
unique_values = df['type'].unique()

# Display the unique values
print("\nUnique values in 'type' column:")
print(unique_values)

Unique values in 'type' column:
['Toro Red' 'Tempranillo' 'Ribera Del Duero Red' 'Pedro Ximenez' 'Red'
 'Sherry' 'Priorat Red' 'Rioja Red' 'Rioja White' 'Grenache' nan 'Cava'
 'Verdejo' 'Syrah' 'Monastrell' 'Mencia' 'Sparkling' 'Montsant Red'
 'Albarino' 'Chardonnay' 'Cabernet Sauvignon' 'Sauvignon Blanc']

In [13]:
null_type = df['type'].isnull()

# Display rows with null values in the 'type' column
print("\nRows with null values in the 'type' column:")
print(df[null_type])

Rows with null values in the 'type' column:
                      winery                                wine  year  \
120            Finca Moncloa                    Tintilla de Rota  2016
147          Rafael Palacios           Sorte O Soro Val do Bibei  2019
156     Gutierrez de la Vega  Recondita Armonia Monastrell Dulce  1987
254      Costers del Siurana                      Dolc de L'Obac  2006
288   Francisco Garcia Perez          Adega do Moucho Treixadura  2017
...                      ...                                 ...   ...
7440                Binigrau                              Nounat  2020
7462          Ramon do Casar                          Treixadura  2020
7465                Binigrau                              Nounat  2020
7487          Ramon do Casar                          Treixadura  2020
7490                Binigrau                              Nounat  2020

      rating  num_reviews country      region      price type  body  acidity
120      4.7           92  Espana       Cadiz   43.13000  NaN   NaN      NaN
147      4.7           37  Espana  Valdeorras  194.86000  NaN   NaN      NaN
156      4.7           27  Espana    Alicante   81.90000  NaN   NaN      NaN
254      4.6           94  Espana    Priorato  117.23942  NaN   NaN      NaN
288      4.6           53  Espana     Ribeiro   34.50000  NaN   NaN      NaN
...      ...          ...     ...         ...        ...  ...   ...      ...
7440     4.2          404  Espana    Mallorca   19.90000  NaN   NaN      NaN
7462     4.2          407  Espana     Ribeiro   11.95000  NaN   NaN      NaN
7465     4.2          404  Espana    Mallorca   19.90000  NaN   NaN      NaN
7487     4.2          407  Espana     Ribeiro   11.95000  NaN   NaN      NaN
7490     4.2          404  Espana    Mallorca   19.90000  NaN   NaN      NaN

[545 rows x 11 columns]

In [14]:
unique_values = df['winery'].unique()

# Display the unique values
print("\nUnique values in 'winery' column:")
print(unique_values)
print("\nNumber of unique values in 'winery' column:")
print(len(unique_values))

Unique values in 'winery' column:
['Teso La Monja' 'Artadi' 'Vega Sicilia' 'Pago de Carraovejas'
 'Toro Albala' 'Bodegas El Nido' 'Valdespino' 'Dominio de Pingus'
 'Alvaro Palacios' 'Ordonez' 'Bodegas Valduero' 'Vina Sastre'
 'Sierra Cantabria' 'Descendientes de J. Palacios' 'La Rioja Alta'
 'Marques de Murrieta' 'Vinedos de Paganos' 'Emilio Moro'
 'Quinta de la Quietud' 'Bodegas Mauro' 'Bodega Contador (Benjamin Romeo)'
 'Remirez de Ganuza' 'Bodegas San Roman' 'Pago de Los Capellanes'
 'Bodega Numanthia' 'Alto Moncayo' 'Mas Doix' 'Finca Moncloa'
 'Bodegas Roda' 'Martinet' 'Recaredo' 'Clos Erasmus' 'Barbadillo'
 'Gonzalez-Byass' 'Bodegas Amaren' 'Alvear' 'Equipo Navazos' 'Morca'
 'Territorio Luthier' 'Rafael Palacios' 'Terra Remota'
 'Dehesa de Los Canonigos' 'Miguel Merino' 'Gutierrez de la Vega' 'Alion'
 'Aalto' 'Carmelo Rodero' 'Dominio del Bendito' "Mas d'en Gil"
 'Casa Castillo' 'Matarromera' 'Nin-Ortiz' 'Vinas del Vero'
 'Marques de Riscal' 'Arzuaga' 'Bodegas Mas Alta' 'Dominio de Calogia'
 'Tomas Postigo' 'Cal Pla' 'Ossian' 'Cepa 21' 'Bodegas Vilano' 'Allende'
 'Costers del Siurana' 'Hacienda Monasterio' 'Castillo Perelada' 'Osborne'
 'Ysios' 'Marques de Grinon' 'Contino' 'Gramona' 'Dominio del Aguila'
 'Hacienda Solano' 'Francisco Garcia Perez' 'Anima Negra' 'Castano'
 'La Legua' 'Castillo de Cuzcurrita' 'Oxer Wines' 'Bodegas Yuste'
 'Bodegas 6o Elemento - Vino Sexto Elemento'
 'Proyecto Garnachas de Espana' 'Casal de Arman' 'Vall Llach'
 'Pago de Larrainzar' 'Ukan Winery' 'Vina Real' 'Dominio de Atauta'
 'Micro Bio (MicroBio)' 'Terroir Al Limit Soc. Lda' 'Finca Torremilanos'
 'Huerta de Albala' 'Gomez Cruzado' "Castell d'Encus" 'Abadia Retuerta'
 'Enate' 'Benjamin de Rothschild - Vega Sicilia' 'Bodegas Aragonesas'
 'Telmo Rodriguez' 'Acustic Celler' 'Vina Pedrosa' 'Pintia' 'Belondrade'
 'Muga' 'Clos Mogador' 'Bodegas Tradicion' 'Senorio de San Vicente'
 'Francisco Barona' 'Juan Gil' 'Lan' 'R. Lopez de Heredia' 'Adama Wines'
 'Milsetentayseis' 'Espectacle del Montsant' 'Tinto Pesquera'
 'Ferrer Bobet' 'Familia Torres' 'Pazo Barrantes' 'Tio Pepe'
 'Cruz de Alba' 'Emilio Rojo' 'Dominio de Es' 'Jesus Madrazo'
 'Bodegas Naluar & Acediano' 'Marques de Caceres' 'Trus' 'Mestres'
 'Chivite' 'Bodega Ribas' 'Vinas del Cenit' 'Mas del Serral' 'Cervoles'
 'Diez Merito' 'Marques de Burgos' 'Penafiel' 'Tobia'
 'Tresmano - Tr3smano' 'Sei Solo' 'Finca Villacreces'
 'Virgen de la Asuncion' 'Romate' 'Sara Perez y Rene Barbier'
 'Dehesa del Carrizal' 'Tarsus' 'Beronia' 'Monte Real' 'Divina Proporcion'
 'Vina al Lado de la Casa' 'Marques de la Concordia' 'Agusti Torello Mata'
 'Dominio de Cair' 'Valquejigoso' 'Veigamoura' 'Vizcarra' 'Legaris'
 'Federico Paternina' 'Vinicola Real' 'Losada' "Clos d'Agon"
 'Sacristia AB' 'Uvaguilera Aguilera' 'Emilio Hidalgo' 'Altos del Terral'
 'El Regajal' 'Valderiz' 'Jose Pariente' 'Amos Baneres' 'Scala Dei'
 'Bodegas Valdelana' 'Abel Mendoza Monge' 'Anayon' 'Sierra Salinas'
 'Vinos Sanz' 'Cerro San Cristobal' 'Altos de Rioja'
 'Bodegas Celler Francisco Castillo - Clos Dominic' 'La Vinya del Vuit'
 'Venus la Universal' 'Pedralonga' 'Atalaya' 'Matsu' 'Marques de Vargas'
 'Volver' 'Tridente' 'Ausas' 'Cillar de Silos' 'Imperial' 'Ramos-Paul'
 'Bodega de Bardos' 'Rodriguez Sanzo' 'Antidoto' 'Bosque de Matasnos'
 'Altanza' 'Remelluri' 'Perinet' 'La Vicalanda' 'Monovar' 'Alvaro Domecq'
 'Los Aguilares' 'Bodega Rento' 'Dominio do Bibei' 'Marco Abella'
 'Javier Sanz Viticultor' 'Protos' 'Harveys' 'Orben' 'Jaro'
 'Bodegas Ximenez-Spinola' 'Bodegas El Paraguas' 'Mustiguillo'
 'Vina Pomal' 'Astrales' 'Merum Priorati' 'Hacienda Lopez de Haro'
 'Cayetano del Pino' 'La Unica' 'Pazo Senorans' 'Fefinanes' 'Resalte'
 'Figuero' 'Pinea' 'Portal del Priorat' 'Cims de Porrera' 'Casa Rojo'
 'Murua' 'Vinyes Domenech' 'Pago de Vallegarcia' 'Eulogio Pomares'
 'Sangenis I Vaque' 'Delgado Zuleta' 'VALENCISO' 'Mas Perinet'
 'Luis A. Rodriguez Vazquez' 'Chozas Carrascal' 'Alonso del Yerro'
 'Clos Figueras' 'Bodegas Monte La Reina' 'Ontanon' 'Alta Alella'
 'Bodega Elias Mora' 'Joan Simo' 'Can Axartell' 'Juan Pinero' 'Mas Llunes'
 'Bodegas Frontaura' 'Roig Parals' 'Avgvstvs' 'Jorge Ordonez'
 'Ramon Bilbao' 'Leda' 'Enric Soler' 'Es Fangar'
 'Cal Batllet - Celler Ripoll Sans' 'Llopart' 'Portia' 'Ostatu'
 'Finca Valpiedra' 'Baigorri' 'Vivaltus' 'Comenge'
 'Collbaix Celler El Moli' 'Martinez Lacuesta' 'Pujanza' 'Albet i Noya'
 'Olivier Riviere' 'Bodegas Tierra' 'Torre de Ona'
 'Do Ferreiro (Bodegas Gerardo Mendez)' 'Martin Codax'
 'Vinedos Hermanos Hernaiz' 'Freixenet' 'Azpilicueta' 'Veronica Salgado'
 'Clos Galena' 'Bodegas Imperiales - Abadia de San Quirce' 'Marta Mate'
 'Venta Las Vacas' 'Pago Calzadilla' 'Vivanco' 'Fernandez Gao' 'Museum'
 'Farina' 'Galindo San Millan' 'Bodegas Casa Primicia' 'Castell Miquel'
 'Barco del Corneta' "Joan d'Anguera" 'Xaloc' 'Carlos Moro'
 'Bodegas Luis Perez' 'Ladairo' "Conreria d'Scala Dei" 'Traslascuestas'
 'Lopez Cristobal' 'Codorniu' 'Sota els Angels' 'Berceo'
 'Mas Blanch I Jove' 'Carlos Serres' 'David Moreno' 'Edra'
 'Valdelosfrailes' 'Briego' 'Guillem Carol - Cellers Carol Valles'
 'Barahonda' 'Particular' 'Bodegas Frontonio' 'Bodegas Asenjo & Manso'
 'Luis Canas' 'Garmon' 'Williams & Humbert' 'Condado de Haza' 'Lustau'
 'Bodegas Faustino' 'St. Petroni' 'Llanos Negros' 'Aster' 'Avancia'
 'Marques de Tomares' 'Quinta Sardonia' 'Abadal' 'Hermanos Pecina'
 'Biniagual' 'Breca' 'Pradorey' 'Terras Gauda' 'Bodega Tesalia'
 'Pazo de Rubianes' 'Godeval' 'Bodegas Olarra' 'Taron' 'Sonsierra'
 'Vins Miquel Gelabert' 'El Grillo y La Luna' 'De Moya' 'Campillo'
 'Jean Leon' 'Bodegas Ateca' 'Bodega Campo Eliseo' 'Fernandez de Pierola'
 'De Muller' 'Monteabellon' 'Pepe Mendoza Casa Agricola' 'Vinos Guerra'
 'Neo' "Terra d'Uro" 'Zarate' 'Noelia Bebelia' 'Marti Fabra'
 'Palmeri Sicilia' 'Mas Que Vinos' 'Bodegas Estraunza' 'Pittacum'
 'Bodega Sommos' 'Celler de Capcanes' 'Arinzano' 'Pago del Vostal' 'Habla'
 'Rodriguez de Vera' 'Callejuela' 'El Maestro Sierra' 'Paco & Lola'
 'Valtravieso' 'Costers del Priorat' 'Bodegas Urium' 'Bodega Otazu'
 'Perez Barquero' 'Oller del Mas' 'Bodegas Clunia' 'Bodegas Ochoa'
 "Ca l'Apotecari" 'Josep Grau Viticultor' 'Fos' 'Hacienda Grimon'
 'Capafons-Osso' 'Can Rafols dels Caus' 'Raul Perez' 'Dominio de la Vega'
 'Juve & Camps' 'Mas de les Pereres' 'Guilera'
 "l'Infernal Combier Fischer Gerin" 'Jorge Piernas' 'Balandro'
 'M. Antonio de la Riva' 'Espelt' 'Bodegas Arfe' 'Real de Asua'
 'Vinyes dels Aspres' 'Valserrano' 'Shaya' 'Finca Rio Negro' 'Loxera'
 'Dominio Fournier' 'Bodegas Yzaguirre' 'Neton' 'Bodega Aida i Luis'
 'Cartoixa de Montsalvat' 'El Lagar de Isilla' 'Anibal de Otero'
 'Altos del Enebro' 'Albamar' 'Can Bas' 'Atlantida' 'Atlan & Artisan'
 'Olivardots' 'Lar de Paula' 'La Val' 'Tres Piedras' 'Javi Revert'
 'Lambuena' 'Attis' 'San Cobate' 'Santa Petronila' 'Jimenez-Landi'
 'Hidalgo (La Gitana)' 'Gallina de Piel' 'Arid' 'Bodegas Reyes'
 'Hugas de Batlle' 'Bodegas Arrocal' 'Buil & Gine' 'Castell del Remei'
 'Valdubon' 'Bodegas Y Vinedos Alilian' 'Sebio' 'Goyo Garcia Viadero'
 'Santiago Ruiz' 'Mauro Estevez' 'Mas Bertran' 'Bodegas Gama' 'Edetaria'
 'Hacienda Zorita Natural Reserve' 'Ton Rimbau' 'Can Xanet' 'A Coroa'
 'Alonso & Pedrajo' 'Mandia Vell' 'Bodega Juan Carlos Sancha'
 'Valdecuevas' 'Algueira' 'Mocen' 'Estones' 'Bodega Tameran' 'Inurrieta'
 'Flor de Chasna' 'Lagar de Sabariz' 'Naia' 'AGE' 'Navajas'
 'Vinyes del Terrer' 'Cepas Familiares' 'Dominio de Loalva' 'Zifar'
 'Bordalas Garcia' 'Rimarts' 'Pinna Fidelis' 'Loess' 'Dominio de Anza'
 'Samsara' 'Cuentavinas' 'Felix Solis' 'El Coto' 'Mar de Frades'
 'Montecastro' 'Bodegas La Horra' 'Baluarte' 'Hispano Suizas' 'Murviedro'
 'Diez Caballero' 'Vegalfaro' 'Palacios Remondo' 'Fernando de Castilla'
 'Bohorquez' 'Adega Familiar Eladio Pineiro' 'Culebron' 'Enrique Mendoza'
 'Clos Pons' 'Ramon do Casar' 'Binigrau']

Number of unique values in 'winery' column:
480

In [15]:
null_type = df['winery'].isnull()

# Display rows with null values in the 'type' column
print("\nRows with null values in the 'winery' column:")
print(df[null_type])

Rows with null values in the 'winery' column:
Empty DataFrame
Columns: [winery, wine, year, rating, num_reviews, country, region, price, type, body, acidity]
Index: []

In [16]:
unique_values = df['year'].unique()

# Display the unique values
print("\nUnique values in 'year' column:")
print(unique_values)

Unique values in 'year' column:
['2013' '2018' '2009' '1999' '1996' '1998' '2010' '1995' '2015' '2011'
 '2016' '1970' '1946' '1962' '2019' '2004' 'N.V.' '1931' '1979' '2005'
 '2020' '2014' '1985' '1929' '2007' '2012' '2017' '2008' nan '2006' '2000'
 '2003' '2002' '1991' '1994' '1990' '1989' '1987' '1986' '1981' '2001'
 '1968' '1964' '1982' '1974' '1983' '1955' '1980' '1972' '1953' '1958'
 '1942' '1965' '1992' '1973' '1997' '1967' '1975' '1910' '1961' '1954'
 '1988' '1969' '1951' '1928' '1976' '1949' '2021' '1959' '1922' '1978'
 '1925']

In [17]:
null_type = df['year'].isnull()

# Display rows with null values in the 'type' column
print("\nRows with null values in the 'year' column:")
print(df[null_type])

Rows with null values in the 'year' column:
           winery                            wine year  rating  num_reviews  \
46   Vega Sicilia  Unico Reserva Especial Edicion  NaN     4.7        12421
851      La Unica                  Fourth Edition  NaN     4.4          131

    country            region  price                  type  body  acidity
46   Espana  Ribera del Duero  423.5  Ribera Del Duero Red   5.0      3.0
851  Espana    Vino de Espana   40.0           Tempranillo   4.0      2.0

In [27]:

# Convert 'year' column to numeric, coercing errors to NaN
df['year'] = pd.to_numeric(df['year'], errors='coerce')

# Calculate the mean of the numeric 'year' column
year_mean = df['year'].mean()

# Fill NaN values in the 'year' column with the mean
df['year'] = df['year'].fillna(year_mean)

# Display the DataFrame after filling NaN values
print("\nDataFrame after filling NaN values in 'year' with the mean:")
print(df)

DataFrame after filling NaN values in 'year' with the mean:
                    winery             wine    year  rating  num_reviews  \
0            Teso La Monja            Tinto  2013.0     4.9           58
1                   Artadi    Vina El Pison  2018.0     4.9           31
2             Vega Sicilia            Unico  2009.0     4.8         1793
3             Vega Sicilia            Unico  1999.0     4.8         1705
4             Vega Sicilia            Unico  1996.0     4.8         1309
...                    ...              ...     ...     ...          ...
7495               Contino          Reserva  2016.0     4.2          392
7496  Conreria d'Scala Dei    Les Brugueres  2018.0     4.2          390
7497           Mustiguillo  Finca Terrerazo  2017.0     4.2          390
7498           Matarromera     Gran Reserva  2011.0     4.2          389
7499              Sei Solo         Preludio  2016.0     4.2          388

     country            region   price                  type  body  acidity
0     Espana              Toro  995.00              Toro Red   5.0      3.0
1     Espana    Vino de Espana  313.50           Tempranillo   4.0      2.0
2     Espana  Ribera del Duero  324.95  Ribera Del Duero Red   5.0      3.0
3     Espana  Ribera del Duero  692.96  Ribera Del Duero Red   5.0      3.0
4     Espana  Ribera del Duero  778.06  Ribera Del Duero Red   5.0      3.0
...      ...               ...     ...                   ...   ...      ...
7495  Espana             Rioja   19.98             Rioja Red   4.0      3.0
7496  Espana          Priorato   16.76           Priorat Red   4.0      3.0
7497  Espana      El Terrerazo   24.45                   Red   4.0      3.0
7498  Espana  Ribera del Duero   64.50  Ribera Del Duero Red   5.0      3.0
7499  Espana  Ribera del Duero   31.63  Ribera Del Duero Red   5.0      3.0

[7500 rows x 11 columns]

In [28]:
null_type = df['year'].isnull()

# Display rows with null values in the 'type' column
print("\nRows with null values in the 'year' column:")
print(df[null_type])

Rows with null values in the 'year' column:
Empty DataFrame
Columns: [winery, wine, year, rating, num_reviews, country, region, price, type, body, acidity]
Index: []

In [30]:
unique_values = df['rating'].unique()

# Display the unique values
print("\nUnique values in 'rating' column:")
print(unique_values)

Unique values in 'rating' column:
[4.9 4.8 4.7 4.6 4.5 4.4 4.3 4.2]

In [31]:
null_type = df['rating'].isnull()

# Display rows with null values in the 'type' column
print("\nRows with null values in the 'rating' column:")
print(df[null_type])

Rows with null values in the 'rating' column:
Empty DataFrame
Columns: [winery, wine, year, rating, num_reviews, country, region, price, type, body, acidity]
Index: []